### ISSUE TITLE
Ambiente virtualizado

### ISSUE THREAD

**Issue by jamessom** [luisconcha/skeleton_laravel_acl#1]
Seria bem interessante ter o ambiente via docker+docker-compose e/ou vagrant

- [Docker Compose e Laravel](https://medium.com/@juniorb2s/docker-compose-e-laravel-e32b683b2486)
- [homestead](https://laravel.com/docs/5.7/homestead)

:stuck_out_tongue_winking_eye:

**Comment by luisconcha** [comment]
Sim, com certeza, o projeto ainda  esta em desenvolvimento, quando finalizar vou integrar com uma delas :)
